UPDATE sites SET site_logo='/mediacenter/media/images/65/logo/836_1417151328_74454780360ba434.png',footercontent='<p>©2014 Tân Minh - ĐCVP: Tòa nhà IMS – Số 473 Nguyễn Trãi – Thanh Xuân – Hà Nội. ĐTVP: 04. 35526657 - ĐTSX:04.6655672</p>\r\n',contact='<p><strong><span style=\"color: rgb(85, 85, 85); font-family: Arial, \'Helvetica Neue\', Helvetica, sans-serif; line-height: 22px; text-align: justify;\">Công ty Cổ phần truyền thông Du Lịch Việt&nbsp;</span></strong></p>\r\n\r\n<p><strong><span style=\"color: rgb(85, 85, 85); font-family: Arial, \'Helvetica Neue\', Helvetica, sans-serif; line-height: 22px; text-align: justify;\">Tên giao dịch:&nbsp;Viet Media Travel Corporation. </span></strong></p>\r\n\r\n<p><strong><span style=\"color: rgb(85, 85, 85); font-family: Arial, \'Helvetica Neue\', Helvetica, sans-serif; line-height: 22px; text-align: justify;\">Trụ sở chính:&nbsp;175 -&nbsp;Nguyễn Thái Bình -&nbsp;Quận 1&nbsp;Tp.HCM.</span></strong></p>\r\n\r\n<p style=\"text-align: justify; \"><font color=\"#555555\" face=\"Arial, Helvetica Neue, Helvetica, sans-serif\"><span style=\"line-height: 22px;\"><b>Điện thoại: 0969.968.655</b></span></font></p>\r\n\r\n<p><em>Để có thể đáp ứng được các yêu cầu và các ý kiến đóng góp của quý vị một cách nhanh chóng xin vui lòng điền vào mẫu dưới đây và nhấn vào nút gửi đến chúng tôi.</em><br />\r\n&nbsp;</p>\r\n',admin_default='news' WHERE site_id=[site_id];

INSERT INTO maps (id,site_id, user_id, latlng, `name`, address, email, phone, website, headoffice, `order`, created_time, modified_time) VALUES (null,[site_id],[user_id],'21.008591,105.830015','Công ty Công Nghệ 3 Nhất','số 79 - Ngõ 82 - Phạm Ngọc Thạch - Đống Đa - Hà Nội','support@web3nhat.com','0948854888','web3nhat.vn',0,0,[now],[now]);


INSERT INTO banner_groups (banner_group_id, banner_group_name, banner_group_description, site_id, user_id, width, height, created_time)  VALUES (null, 'Nhóm chính', '', '[site_id]', '[user_id]', '1000', '0', '[now]');
set @banner_groups3 = LAST_INSERT_ID();


INSERT INTO banners (banner_id, site_id, banner_group_id, banner_name, banner_description, banner_src, banner_width, banner_height, banner_link, banner_type, banner_order, banner_rules, banner_target, created_time, banner_showall) VALUES (null, [site_id],@banner_groups3, 'Phòng khách vip 2','','/mediacenter/media/files/65/banners/835_1417150916_85547801c466b03.jpg',1000,0,'',1,2,'',0,[now],1);
set @banners16 = LAST_INSERT_ID();
INSERT INTO banners (banner_id, site_id, banner_group_id, banner_name, banner_description, banner_src, banner_width, banner_height, banner_link, banner_type, banner_order, banner_rules, banner_target, created_time, banner_showall) VALUES (null, [site_id],@banner_groups3, 'Phòng khách vip 1','Phòng khách vip tầng 1','/mediacenter/media/files/65/banners/331_1417150971_13547801fb1da5d.jpg',1000,0,'',1,1,'',0,[now],1);
set @banners17 = LAST_INSERT_ID();
INSERT INTO banners (banner_id, site_id, banner_group_id, banner_name, banner_description, banner_src, banner_width, banner_height, banner_link, banner_type, banner_order, banner_rules, banner_target, created_time, banner_showall) VALUES (null, [site_id],@banner_groups3, 'Bệnh viện đa khoa Thanh Xuân','','/mediacenter/media/files/65/banners/739_1417156780_967547818acdc49a.jpg',1000,0,'',1,3,'',0,[now],1);
set @banners18 = LAST_INSERT_ID();


INSERT INTO news (news_id, news_category_id, news_title, news_sortdesc, news_desc, `alias`, `status`, meta_keywords, meta_description, site_id, user_id, image_path, image_name, created_time, modified_time, modified_by, news_hot, news_source, poster, publicdate) VALUES (null,0,'Đại hội Công đoàn năm 2014','Ban chấp hành Công đoàn mới gửi tặng đóa hoa rực rỡ tới bà Đặng Thị Minh Tâm – đại diện Ban chấp hành Công đoàn nhiệm kỳ 2012 – 2014, thể hiện sự trân trọng những đóng góp xây dựng Công đoàn trong suốt thời gian qua.','<p>Đại hội Công đoàn tập trung vào hai nội dung chính:</p>\r\n\r\n<p>+ Báo cáo hoạt động Công đoàn nhiệm kỳ 2012 – 2014 và phương hướng, nhiệm vụ Công đoàn năm 2014 – 2016</p>\r\n\r\n<p>+ Bầu cử Ban chấp hành Công đoàn nhiệm kỳ 2014 – 2016</p>\r\n\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp; Ban chấp hành Công đoàn nhiệm kỳ 2012 – 2014, đại diện là Chủ tịch Công đoàn Đặng Thị Minh Tâm đã tổng kết lại hoạt động Công đoàn trong thời gian qua. Nhìn chung, Công đoàn có những hành động thiết thực thể hiện sự quan tâm đời sống của CB-CNV như: việc hiếu - hỉ, thăm hỏi nhân viên khi sinh nở, ốm đau… Bên cạnh đó, Công đoàn còn tổ chức các hoạt động văn hóa – văn nghệ, thể dục thể thao (đội bóng Tân Minh)… Những hoạt động trên tạo ra sự gắn kết, thân thiết giữa các thành viên Công ty.</p>\r\n\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp; Toàn thể CB-CNV đã thống nhất bầu ra Ban chấp hành Công đoàn mới cho nhiệm kỳ 2014 – 2016 gồm:</p>\r\n\r\n<p>+ Chủ tịch Công đoàn: Nguyễn Quỳnh Trang</p>\r\n\r\n<p>+ Ủy viên: Nguyễn Thị Nguyên</p>\r\n\r\n<p>+ Ủy viên: Vi Thị Thanh Hà</p>\r\n\r\n<p>+ Ủy viên: Phạm Đăng Hồng</p>\r\n\r\n<p>+ Ủy viên: Lê Văn Long</p>\r\n\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp; Những thành viên Ban chấp hành mới mang đến sự trẻ trung, năng động, nhiệt tình sẽ tiếp tục xây dựng, thực hiện những kế hoạch, hoạt động của Công đoàn trong nhiệm kỳ 2014 – 2016:</p>\r\n\r\n<p>+ Tiếp tục duy trì các hoạt động chăm lo đời sống CB-CNV</p>\r\n\r\n<p>+ Xây dựng thêm các hoạt động mới bổ ích, nâng cao tinh thần, sự đoàn kết cho CB-CNV</p>\r\n\r\n<p>+ Tiếp thu ý kiến đóng góp của CB-CNV để thay đổi, chỉnh sửa các hoạt động thiết thực, hợp lý hơn</p>\r\n\r\n<p>+ Thường xuyên trao đổi với Ban lãnh đạo Công ty để tạo điều kiện, cải thiện môi trường làm việc chung</p>\r\n\r\n<p>+ Đẩy mạnh phong trào tham gia các khóa học, khóa đào tạo nâng cao kiến thức chuyên môn, kỹ năng cho CB-CNV</p>\r\n\r\n<p>&nbsp;&nbsp;&nbsp; Ban lãnh đạo Công ty cùng toàn thể CB-CNV tin tưởng vào phương hướng hoạt động của Ban chấp hành Công đoàn nhiệm kỳ 2014 – 2016.</p>\r\n\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp; Đại hội Công đoàn thành công tốt đẹp !</p>\r\n','dai-hoi-cong-doan-nam-2014',1,'','',[site_id],[user_id],'/media/images/65/news/ava/','210_1417167748_74254784384e008d.jpg',[now], [now],[user_id],0,'','',[now]);set @news16 = LAST_INSERT_ID();
INSERT INTO news (news_id, news_category_id, news_title, news_sortdesc, news_desc, `alias`, `status`, meta_keywords, meta_description, site_id, user_id, image_path, image_name, created_time, modified_time, modified_by, news_hot, news_source, poster, publicdate) VALUES (null,0,'Chào mừng đại lễ 30/4 và Quốc tế lao động 1/5','Thông báo lịch nghỉ lễ 30/4 và Quốc tế lao động 1/5 năm 2014 của Công ty Cổ phần Đầu tư Tân Minh','<p>Nhân dịp kỷ niệm ngày giải phóng miền Nam, thống nhất đất nước (30/04/1975 - 30/04/2014) và kỷ niệm ngày Quốc tế lao động (1/5/1886 - 1/5/2014), thay mặt&nbsp; Ban Lãnh đạo Công ty Cổ phần Đầu tư Tân Minh xin gửi tới các CB-CNV lời chúc tốt đẹp nhất. Chúc ﻿ toàn thể﻿ các CB-CNV có những ngày nghỉ vui vẻ và gặp nhiều may mắn. Chúc Tân Minh ngày càng phát triển thịnh vượng và bền vững.</p>\r\n','chao-mung-dai-le-304-va-quoc-te-lao-dong-15',1,'','',[site_id],[user_id],'/media/images/65/news/ava/','475_1417162937_67547830b91234d.jpg',[now], [now],[user_id],0,'','',[now]);set @news15 = LAST_INSERT_ID();





INSERT INTO product_categories (cat_id, site_id, attribute_set_id, cat_parent, cat_name, `alias`, cat_order, cat_description, cat_countchild, image_path, image_name, `status`, created_time, modified_time, showinhome, meta_keywords, meta_description, icon_path, icon_name) VALUES (null,[site_id],NULL,0,'Thiết kế','thiet-ke',1,'',0,'','',1,[now], [now],0,'','','','');
set @product_categories878 = LAST_INSERT_ID();
INSERT INTO product_categories (cat_id, site_id, attribute_set_id, cat_parent, cat_name, `alias`, cat_order, cat_description, cat_countchild, image_path, image_name, `status`, created_time, modified_time, showinhome, meta_keywords, meta_description, icon_path, icon_name) VALUES (null,[site_id],NULL,0,'Quy hoạch','quy-hoach',2,'',0,'','',1,[now], [now],0,'','','','');
set @product_categories879 = LAST_INSERT_ID();



INSERT INTO product (`id`, `attribute_set_id`, `name`, `code`, `alias`, `ishot`, `price`, `price_market`, `price_discount`, `price_discount_percent`, `avatar_id`, `avatar_path`, `avatar_name`, `currency`, `include_vat`, `quantity`, `position`, `product_category_id`, `category_track`, `status`, `state`, `created_user`, `created_time`, `modified_user`, `modified_time`, `site_id`, `meta_keywords`, `meta_description`, `meta_title`, `list_product_relate`, `isnew`, `manufacturer_id`, `cus_field1`, `cus_field2`, `cus_field3`, `cus_field4`, `cus_field5`, `cus_field6`, `cus_field7`, `cus_field8`, `cus_field9`, `cus_field10`, `cus_field11`, `cus_field12`, `cus_field13`, `cus_field14`, `cus_field15`, `cus_field16`, `cus_field17`, `cus_field18`, `cus_field19`, `cus_field20`, `cus_field21`, `cus_field22`, `cus_field23`, `cus_field24`, `cus_field25`, `cus_field26`, `cus_field27`, `cus_field28`, `cus_field29`, `cus_field30`, `cus_field31`, `cus_field32`, `cus_field33`, `cus_field34`, `cus_field35`, `cus_field36`, `cus_field37`, `cus_field38`) VALUES (null,null,'Nhà phố','','nha-pho',0,0.00,0.00,0.00,0,0,'/media/images/products/65/1/','171_1438939753_59755c47a697fa54.jpg','',0,0,1000,@product_categories878,CONCAT(@product_categories878),1,1,[user_id],[now],[user_id],[now],[site_id],'','','','',1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0);
set @product687 = LAST_INSERT_ID();
INSERT INTO product (`id`, `attribute_set_id`, `name`, `code`, `alias`, `ishot`, `price`, `price_market`, `price_discount`, `price_discount_percent`, `avatar_id`, `avatar_path`, `avatar_name`, `currency`, `include_vat`, `quantity`, `position`, `product_category_id`, `category_track`, `status`, `state`, `created_user`, `created_time`, `modified_user`, `modified_time`, `site_id`, `meta_keywords`, `meta_description`, `meta_title`, `list_product_relate`, `isnew`, `manufacturer_id`, `cus_field1`, `cus_field2`, `cus_field3`, `cus_field4`, `cus_field5`, `cus_field6`, `cus_field7`, `cus_field8`, `cus_field9`, `cus_field10`, `cus_field11`, `cus_field12`, `cus_field13`, `cus_field14`, `cus_field15`, `cus_field16`, `cus_field17`, `cus_field18`, `cus_field19`, `cus_field20`, `cus_field21`, `cus_field22`, `cus_field23`, `cus_field24`, `cus_field25`, `cus_field26`, `cus_field27`, `cus_field28`, `cus_field29`, `cus_field30`, `cus_field31`, `cus_field32`, `cus_field33`, `cus_field34`, `cus_field35`, `cus_field36`, `cus_field37`, `cus_field38`) VALUES (null,null,'Biệt thự','','biet-thu',0,0.00,0.00,0.00,0,0,'/media/images/products/65/1/','786_1438939660_29655c47a0cb8acb.jpg','',0,0,1000,@product_categories878,CONCAT(@product_categories878),1,1,[user_id],[now],[user_id],[now],[site_id],'','','','',1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0);
set @product686 = LAST_INSERT_ID();
INSERT INTO product (`id`, `attribute_set_id`, `name`, `code`, `alias`, `ishot`, `price`, `price_market`, `price_discount`, `price_discount_percent`, `avatar_id`, `avatar_path`, `avatar_name`, `currency`, `include_vat`, `quantity`, `position`, `product_category_id`, `category_track`, `status`, `state`, `created_user`, `created_time`, `modified_user`, `modified_time`, `site_id`, `meta_keywords`, `meta_description`, `meta_title`, `list_product_relate`, `isnew`, `manufacturer_id`, `cus_field1`, `cus_field2`, `cus_field3`, `cus_field4`, `cus_field5`, `cus_field6`, `cus_field7`, `cus_field8`, `cus_field9`, `cus_field10`, `cus_field11`, `cus_field12`, `cus_field13`, `cus_field14`, `cus_field15`, `cus_field16`, `cus_field17`, `cus_field18`, `cus_field19`, `cus_field20`, `cus_field21`, `cus_field22`, `cus_field23`, `cus_field24`, `cus_field25`, `cus_field26`, `cus_field27`, `cus_field28`, `cus_field29`, `cus_field30`, `cus_field31`, `cus_field32`, `cus_field33`, `cus_field34`, `cus_field35`, `cus_field36`, `cus_field37`, `cus_field38`) VALUES (null,null,'Chung cư cao cấp','','chung-cu-cao-cap',0,0.00,0.00,0.00,0,0,'/media/images/products/65/1/','977_1438939450_30255c4793a6da30.jpg','',0,0,1000,@product_categories878,CONCAT(@product_categories878),1,1,[user_id],[now],[user_id],[now],[site_id],'','','','',1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0);
set @product685 = LAST_INSERT_ID();
INSERT INTO product (`id`, `attribute_set_id`, `name`, `code`, `alias`, `ishot`, `price`, `price_market`, `price_discount`, `price_discount_percent`, `avatar_id`, `avatar_path`, `avatar_name`, `currency`, `include_vat`, `quantity`, `position`, `product_category_id`, `category_track`, `status`, `state`, `created_user`, `created_time`, `modified_user`, `modified_time`, `site_id`, `meta_keywords`, `meta_description`, `meta_title`, `list_product_relate`, `isnew`, `manufacturer_id`, `cus_field1`, `cus_field2`, `cus_field3`, `cus_field4`, `cus_field5`, `cus_field6`, `cus_field7`, `cus_field8`, `cus_field9`, `cus_field10`, `cus_field11`, `cus_field12`, `cus_field13`, `cus_field14`, `cus_field15`, `cus_field16`, `cus_field17`, `cus_field18`, `cus_field19`, `cus_field20`, `cus_field21`, `cus_field22`, `cus_field23`, `cus_field24`, `cus_field25`, `cus_field26`, `cus_field27`, `cus_field28`, `cus_field29`, `cus_field30`, `cus_field31`, `cus_field32`, `cus_field33`, `cus_field34`, `cus_field35`, `cus_field36`, `cus_field37`, `cus_field38`) VALUES (null,null,'Biệt thự Hải Dương','','biet-thu-hai-duong',0,0.00,0.00,0.00,0,0,'/media/images/products/65/1/','41_1438938219_28555c4746b01c2c.jpg','',0,0,1000,@product_categories879,CONCAT(@product_categories879),1,1,[user_id],[now],[user_id],[now],[site_id],'','','','',1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0);
set @product684 = LAST_INSERT_ID();
INSERT INTO product (`id`, `attribute_set_id`, `name`, `code`, `alias`, `ishot`, `price`, `price_market`, `price_discount`, `price_discount_percent`, `avatar_id`, `avatar_path`, `avatar_name`, `currency`, `include_vat`, `quantity`, `position`, `product_category_id`, `category_track`, `status`, `state`, `created_user`, `created_time`, `modified_user`, `modified_time`, `site_id`, `meta_keywords`, `meta_description`, `meta_title`, `list_product_relate`, `isnew`, `manufacturer_id`, `cus_field1`, `cus_field2`, `cus_field3`, `cus_field4`, `cus_field5`, `cus_field6`, `cus_field7`, `cus_field8`, `cus_field9`, `cus_field10`, `cus_field11`, `cus_field12`, `cus_field13`, `cus_field14`, `cus_field15`, `cus_field16`, `cus_field17`, `cus_field18`, `cus_field19`, `cus_field20`, `cus_field21`, `cus_field22`, `cus_field23`, `cus_field24`, `cus_field25`, `cus_field26`, `cus_field27`, `cus_field28`, `cus_field29`, `cus_field30`, `cus_field31`, `cus_field32`, `cus_field33`, `cus_field34`, `cus_field35`, `cus_field36`, `cus_field37`, `cus_field38`) VALUES (null,null,'Thiết kế - Thi công nội thất chung cư Royal City','','thiet-ke---thi-cong-noi-that-chung-cu-royal-city',0,0.00,0.00,0.00,0,0,'/media/images/products/65/1/','571_1438938059_94855c473cb8e718.jpg','',0,0,1000,@product_categories878,CONCAT(@product_categories878),1,1,[user_id],[now],[user_id],[now],[site_id],'','','','',1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0);
set @product683 = LAST_INSERT_ID();
INSERT INTO product (`id`, `attribute_set_id`, `name`, `code`, `alias`, `ishot`, `price`, `price_market`, `price_discount`, `price_discount_percent`, `avatar_id`, `avatar_path`, `avatar_name`, `currency`, `include_vat`, `quantity`, `position`, `product_category_id`, `category_track`, `status`, `state`, `created_user`, `created_time`, `modified_user`, `modified_time`, `site_id`, `meta_keywords`, `meta_description`, `meta_title`, `list_product_relate`, `isnew`, `manufacturer_id`, `cus_field1`, `cus_field2`, `cus_field3`, `cus_field4`, `cus_field5`, `cus_field6`, `cus_field7`, `cus_field8`, `cus_field9`, `cus_field10`, `cus_field11`, `cus_field12`, `cus_field13`, `cus_field14`, `cus_field15`, `cus_field16`, `cus_field17`, `cus_field18`, `cus_field19`, `cus_field20`, `cus_field21`, `cus_field22`, `cus_field23`, `cus_field24`, `cus_field25`, `cus_field26`, `cus_field27`, `cus_field28`, `cus_field29`, `cus_field30`, `cus_field31`, `cus_field32`, `cus_field33`, `cus_field34`, `cus_field35`, `cus_field36`, `cus_field37`, `cus_field38`) VALUES (null,null,'Thiết kế - Thi công nội thất chung cư Royal City','','thiet-ke---thi-cong-noi-that-chung-cu-royal-city',0,0.00,0.00,0.00,0,0,'/media/images/products/65/1/','428_1438937777_81155c472b1e4e4d.jpg','',0,0,1000,@product_categories878,CONCAT(@product_categories878),1,1,[user_id],[now],[user_id],[now],[site_id],'','','','',1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,0,0,0,0,0,0,0,0,0);
set @product682 = LAST_INSERT_ID();

INSERT INTO product_info (product_id, product_sortdesc, product_desc, dynamic_field, meta_title, meta_keywords, meta_description, list_product_relate, site_id) VALUES (@product682,'','','','','','','',[site_id]);
INSERT INTO product_info (product_id, product_sortdesc, product_desc, dynamic_field, meta_title, meta_keywords, meta_description, list_product_relate, site_id) VALUES (@product683,'','<p style=\"line-height: 20.7999992370605px;\">Địa điểm: Khu Vườn Đào - Tây Hồ - Hà Nội</p>\r\n\r\n<p style=\"line-height: 20.7999992370605px;\">Thời gian thực hiện: Năm 2014</p>\r\n\r\n<p style=\"line-height: 20.7999992370605px;\">Nội dung công việc: Thiết kế nội thất công trình</p>\r\n','','','','','',[site_id]);
INSERT INTO product_info (product_id, product_sortdesc, product_desc, dynamic_field, meta_title, meta_keywords, meta_description, list_product_relate, site_id) VALUES (@product684,'','','','','','','',[site_id]);
INSERT INTO product_info (product_id, product_sortdesc, product_desc, dynamic_field, meta_title, meta_keywords, meta_description, list_product_relate, site_id) VALUES (@product685,'','','','','','','',[site_id]);
INSERT INTO product_info (product_id, product_sortdesc, product_desc, dynamic_field, meta_title, meta_keywords, meta_description, list_product_relate, site_id) VALUES (@product686,'','','','','','','',[site_id]);
INSERT INTO product_info (product_id, product_sortdesc, product_desc, dynamic_field, meta_title, meta_keywords, meta_description, list_product_relate, site_id) VALUES (@product687,'','','','','','','',[site_id]);

INSERT INTO product_images (img_id, product_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@product682,'785_1438937784_88355c472b836a4c.jpg','/media/images/products/65/1/','7_1427862955_167551b75ab8b7c4.jpg','','71427862955167551b75ab8b7c4jpg',[site_id],[user_id],341,500,[now],[now]);
set @product_images1213 = LAST_INSERT_ID();
INSERT INTO product_images (img_id, product_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@product682,'428_1438937777_81155c472b1e4e4d.jpg','/media/images/products/65/1/','652_1427690986_9495518d5eaa9d83.jpg','','65214276909869495518d5eaa9d83jpg',[site_id],[user_id],375,500,[now],[now]);
set @product_images1214 = LAST_INSERT_ID();
INSERT INTO product_images (img_id, product_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@product683,'571_1438938059_94855c473cb8e718.jpg','/media/images/products/65/1/','801_1427691024_6605518d61015413.jpg','','80114276910246605518d61015413jpg',[site_id],[user_id],333,500,[now],[now]);
set @product_images1215 = LAST_INSERT_ID();
INSERT INTO product_images (img_id, product_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@product684,'41_1438938219_28555c4746b01c2c.jpg','/media/images/products/65/1/','7_1427862955_167551b75ab8b7c4.jpg','','71427862955167551b75ab8b7c4jpg',[site_id],[user_id],341,500,[now],[now]);
set @product_images1216 = LAST_INSERT_ID();
INSERT INTO product_images (img_id, product_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@product685,'977_1438939450_30255c4793a6da30.jpg','/media/images/products/65/1/','tải xuống.jpg','','tai-xuongjpg',[site_id],[user_id],196,258,[now],[now]);
set @product_images1217 = LAST_INSERT_ID();
INSERT INTO product_images (img_id, product_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@product686,'786_1438939660_29655c47a0cb8acb.jpg','/media/images/products/65/1/','550077652883.jpg','','550077652883jpg',[site_id],[user_id],3537,5049,[now],[now]);
set @product_images1218 = LAST_INSERT_ID();
INSERT INTO product_images (img_id, product_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@product687,'171_1438939753_59755c47a697fa54.jpg','/media/images/products/65/1/','702554492637.jpg','','702554492637jpg',[site_id],[user_id],2970,2100,[now],[now]);
set @product_images1219 = LAST_INSERT_ID();

UPDATE product SET avatar_id=@product_images1219 WHERE id=@product687;
UPDATE product SET avatar_id=@product_images1218 WHERE id=@product686;
UPDATE product SET avatar_id=@product_images1217 WHERE id=@product685;
UPDATE product SET avatar_id=@product_images1216 WHERE id=@product684;
UPDATE product SET avatar_id=@product_images1215 WHERE id=@product683;
UPDATE product SET avatar_id=@product_images1214 WHERE id=@product682;


INSERT INTO categorypage (id, title, content, site_id, user_id, `alias`, created_time, modified_time, modified_by, meta_keywords, meta_description, meta_title, image_path, image_name) VALUES (null,'Tổng quan','<p>Chúng tôi với hoạt động duy nhất là nghiên cứu kỹ thuật và thiết kế website. Cho tới nay Web3nhat đã xây dựng website cho nhiều đối tác trong và ngoài nước.</p>\r\n\r\n<p>Bên cạnh đó là hàng loạt website cho những khách hàng tầm cỡ và có thứ hạng truy cập rất cao (Vccorp, Vật giá) dựa trên công nghệ lập trình, Web3nhat cung cấp nhiều giải pháp và công nghệ tối ưu hóa cho việc quản trị – quảng bá website, giảm chi phí nhân sự, giúp cho việc quản trị trở nên đơn giản, dễ hiểu, thậm chí không cần chúng tôi hướng dẫn sử dụng.</p>\r\n\r\n<p>Đội ngũ lập trình viên của Web3nhat có tư duy tốt, kỹ thuật chuyên môn cao, say mê công việc.</p>\r\n\r\n<p>Đội ngũ tư vấn của Web3nhat luôn nhiệt tình, nhiều kinh nghiệm và hiểu rõ giải pháp pr, truyền thông hợp lý sẽ giúp Quý khách đạt được hiệu quả đầu tư cao nhất.</p>\r\n\r\n<p>Đội ngũ thiết kế web của Web3nhat có khả năng tư duy sáng tạo và cảm nhận thẩm mỹ tốt, cùng với nền tảng chuyên môn được đào tạo từ những trung tâm &amp; trường lớp đồ họa chất lượng cao tại Việt Nam.</p>\r\n',[site_id],[user_id],'gioi-thieu',[now],[now],[user_id],'','','','','');
set @categorypage5 = LAST_INSERT_ID();


INSERT INTO albums (album_id, album_name, album_description, album_type, photocount, `alias`, site_id, user_id, meta_keywords, meta_description, avatar_path, avatar_name, avatar_id, created_time, modified_time, cat_id,`order`) VALUES (null,'Album ảnh một số sản phẩm','Miêu tả cho album ảnh này',0,3,'album-anh-mot-so-san-pham',[site_id],[user_id],'','','/media/images/albums/65/1/','671_1438938529_15355c475a1c7bae.jpg',592,[now],[now],0,9999);
set @albums61 = LAST_INSERT_ID();


INSERT INTO images (img_id, album_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@albums61,'972_1438938560_89055c475c03bbfb.jpg','/media/images/albums/65/1/','801_1427691024_6605518d61015413.jpg','','80114276910246605518d61015413jpg',[site_id],[user_id],333,500,[now],[now]);
set @images593 = LAST_INSERT_ID();
INSERT INTO images (img_id, album_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@albums61,'762_1438938547_68255c475b31c9e7.jpg','/media/images/albums/65/1/','652_1427690986_9495518d5eaa9d83.jpg','','65214276909869495518d5eaa9d83jpg',[site_id],[user_id],375,500,[now],[now]);
set @images594 = LAST_INSERT_ID();
INSERT INTO images (img_id, album_id, `name`, `path`, display_name, description, `alias`, site_id, user_id, height, width, created_time, modified_time) VALUES (null,@albums61,'671_1438938529_15355c475a1c7bae.jpg','/media/images/albums/65/1/','7_1427862955_167551b75ab8b7c4.jpg','','71427862955167551b75ab8b7c4jpg',[site_id],[user_id],341,500,[now],[now]);
set @images592 = LAST_INSERT_ID();


INSERT INTO menu_groups (menu_group_id, menu_group_name, menu_group_description, site_id, user_id, config, created_time, modified_time, modified_by, menu_group_type) VALUES (null,'Nhóm menu chính','nhóm chính',[site_id],[user_id],'',[now],[now],[user_id],0);
set @menu_groups3 = LAST_INSERT_ID();

INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Trang Chủ',0,1,'','','[]',1,'trang-chu',1,1,'{\"t\":1,\"oi\":1}','','','','','',[now],[now],[user_id]);
set @menus21 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Giới thiệu',0,1,'','/page/category/detail',CONCAT('{"id":',@categorypage5,',"alias":"gioi-thieu"}'),2,'gioi-thieu',1,1,'','','','','','',[now],[now],[user_id]);
set @menus22 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Hồ sơ sản phẩm',0,1,'','/economy/product','[]',3,'ho-so-san-pham',1,1,'{\"t\":1,\"oi\":9}','','','','','',[now],[now],[user_id]);
set @menus23 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Nông thôn mới',0,1,'','','',0,'kien-truc',1,1,'{\"t\":1,\"oi\":0}','','','','','',[now],[now],[user_id]);
set @menus28 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Đô thị',0,1,'','','',0,'do-thi',1,1,'{\"t\":1,\"oi\":0}','','','','','',[now],[now],[user_id]);
set @menus30 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Văn hóa',0,1,'','','',5,'video',1,1,'{\"t\":1,\"oi\":0}','','','','','',[now],[now],[user_id]);
set @menus102 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Du lịch, nghỉ dưỡng',0,1,'','','',0,'du-lich-nghi-duong',1,1,'{\"t\":1,\"oi\":0}','','','','','',[now],[now],[user_id]);
set @menus827 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Giáo dục - Khoa học công nghệ',0,1,'','','',0,'giao-duc---khoa-hoc-cong-nghe',1,1,'{\"t\":1,\"oi\":0}','','','','','',[now],[now],[user_id]);
set @menus828 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Kiến trúc',@menus23,1,'','','',0,'kien-truc',1,1,'{\"t\":1,\"oi\":0}','','','','','',[now],[now],[user_id]);
set @menus829 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Nội thất',@menus23,1,'','','',0,'noi-that',1,1,'{\"t\":1,\"oi\":0}','','','','','',[now],[now],[user_id]);
set @menus830 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Video',0,1,'','/media/video/all','[]',5,'video',1,1,'{\"t\":1,\"oi\":12}','','','','','',[now],[now],[user_id]);
set @menus832 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Ablum ảnh',0,1,'','/media/album/all','[]',6,'ablum-anh',1,1,'{\"t\":1,\"oi\":11}','','','','','',[now],[now],[user_id]);
set @menus833 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Tuyển dụng ',0,1,'','/work/job','[]',7,'tuyen-dung',1,1,'{\"t\":1,\"oi\":13}','','','','','',[now],[now],[user_id]);
set @menus831 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Liên hệ',0,1,'','/site/site/contact','[]',8,'lien-he',1,1,'{\"t\":1,\"oi\":2}','','','','','',[now],[now],[user_id]);
set @menus834 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Quy hoạch',@menus23,1,'','/economy/product/category',CONCAT('{"id":',@product_categories878,',"alias":"thiet-ke"}'),0,'quy-hoach',1,1,'','','','','','',[now],[now],[user_id]);
set @menus27 = LAST_INSERT_ID();
INSERT INTO menus (menu_id, site_id, user_id, menu_group, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, icon_path, icon_name, background_path, background_name, description, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],@menu_groups3,'Tin tức',0,1,'','/news/news','[]',4,'tin-tuc',1,1,'{\"t\":1,\"oi\":8}','','','','','',[now],[now],[user_id]);
set @menus24 = LAST_INSERT_ID();
UPDATE menus SET parent_id=@menus27 WHERE menu_id=@menus28;
UPDATE menus SET parent_id=@menus27 WHERE menu_id=@menus30;
UPDATE menus SET parent_id=@menus27 WHERE menu_id=@menus102;
UPDATE menus SET parent_id=@menus27 WHERE menu_id=@menus827;
UPDATE menus SET parent_id=@menus27 WHERE menu_id=@menus828;


INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý nội dung',0,1,'#','','[]',0,'quan-ly-noi-dung',1,1,'','icon-newspaper-o',[now],[now],[user_id]);
set @menus_admin175 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý tin tức',@menus_admin175,1,'/content/news','content/news','[]',1,'quan-ly-tin-tuc',1,1,'','icon-newspaper-o',[now],[now],[user_id]);
set @menus_admin53 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Danh mục tin tức',@menus_admin175,1,'/content/newscategory','content/newscategory','[]',2,'danh-muc-tin-tuc',1,1,'','',[now],[now],[user_id]);
set @menus_admin176 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Trang nội dung',@menus_admin175,1,'/content/categorypage','content/categorypage','[]',4,'trang-noi-dung',1,1,'','icon-tag',[now],[now],[user_id]);
set @menus_admin61 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý video',0,1,'/media/video','media/video','[]',0,'quan-ly-video',1,1,'','icon-file-movie-o',[now],[now],[user_id]);
set @menus_admin181 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Sản phẩm',0,1,'#','','[]',2,'san-pham',1,1,'','icon-file-powerpoint-o',[now],[now],[user_id]);
set @menus_admin54 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý sản phẩm',@menus_admin54,1,'/san-pham','economy/product','[]',1,'quan-ly-san-pham',1,1,'','',[now],[now],[user_id]);
set @menus_admin177 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Danh mục sản phẩm',@menus_admin54,1,'/economy/productcategory','economy/productcategory','[]',2,'danh-muc-san-pham',1,1,'','',[now],[now],[user_id]);
set @menus_admin178 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý banner',0,1,'/banner/banner','banner/banner','[]',3,'quan-ly-banner',1,1,'','icon-building-o',[now],[now],[user_id]);
set @menus_admin55 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý giao diện',0,1,'#','','[]',3,'quan-ly-giao-dien',1,1,'','icon-desktop',[now],[now],[user_id]);
set @menus_admin179 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý menu',@menus_admin179,0,'http://w3ni111.web3nhat.net/quantri/interface/menugroup/list/mgid/3','interface/menugroup','[]',1,'quan-ly-menu',1,1,'','icon-list',[now],[now],[user_id]);
set @menus_admin56 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý chân trang',@menus_admin179,1,'/interface/sitesettings/footersetting','interface/sitesettings/footersetting','[]',2,'quan-ly-chan-trang',1,1,'','icon-bookmark',[now],[now],[user_id]);
set @menus_admin59 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Tùy chỉnh CSS',@menus_admin179,1,'/interface/sitesettings/stylecustom','interface/sitesettings/stylecustom','[]',3,'tuy-chinh-css',1,1,'','',[now],[now],[user_id]);
set @menus_admin174 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý ảnh',0,1,'/media/album','media/album','[]',4,'quan-ly-anh',1,1,'','icon-file-photo-o',[now],[now],[user_id]);
set @menus_admin180 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Cấu hình website',0,1,'/setting/setting','setting/setting','[]',5,'cau-hinh-website',1,1,'','icon-gear',[now],[now],[user_id]);
set @menus_admin57 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Thông tin website',@menus_admin57,1,'/setting/setting','setting/setting','[]',1,'thong-tin-website',1,1,'','icon-gears',[now],[now],[user_id]);
set @menus_admin62 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Cấu hình tên miền',@menus_admin57,1,'/setting/setting/domainsetting','setting/setting/domainsetting','[]',1,'cau-hinh-ten-mien',1,1,'','icon-gear',[now],[now],[user_id]);
set @menus_admin100 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Thông tin liên hệ',@menus_admin57,1,'/interface/sitesettings/contact','interface/sitesettings/contact','[]',2,'thong-tin-lien-he',1,1,'','icon-play',[now],[now],[user_id]);
set @menus_admin58 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Bản đồ',@menus_admin57,1,'/setting/map','setting/map','[]',3,'ban-do',1,1,'','icon-flag',[now],[now],[user_id]);
set @menus_admin63 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý tuyển dụng',0,1,'/work/jobs','work/jobs','[]',6,'quan-ly-tuyen-dung',1,1,'','icon-user',[now],[now],[user_id]);
set @menus_admin182 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, `alias`, `status`, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý liên hệ',0,1,'/custom/customform/statistic','custom/customform/statistic','[]',8,'quan-ly-lien-he',1,1,'','icon-book',[now],[now],[user_id]);
set @menus_admin60 = LAST_INSERT_ID();


INSERT INTO forms (form_id, form_code, form_name, form_description, site_id, `status`, created_time, modified_time, user_id) VALUES (null,'fo_14171504385477ffe61c503','Form liên hệ','',[site_id],1,[now],[now],[user_id]);
set @forms2 = LAST_INSERT_ID();

INSERT INTO form_fields (field_id, form_id, field_key, field_label, field_type, field_options, field_required, `order`, site_id, user_id, `status`) VALUES 
(null,@forms2, 'c21','Tên','text','{\"size\":\"large\"}',1,1,[site_id],[user_id],1),
(null,@forms2, 'c62','Email','email','{\"size\":\"large\"}',1,2,[site_id],[user_id],1),
(null,@forms2, 'c103','Số điện thoại','text','{\"size\":\"large\"}',1,3,[site_id],[user_id],1),
(null,@forms2, 'c144','Chủ đề','text','{\"size\":\"large\"}',1,4,[site_id],[user_id],1),
(null,@forms2, 'c185','Nội dung','paragraph','{\"size\":\"large\"}',1,5,[site_id],[user_id],1),
(null,@forms2, 'c226','Gửi yêu cầu','button','{\"size\":\"large\",\"onclick\":\"\",\"button_type\":\"submitform\"}',0,6,[site_id],[user_id],1);


INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Banner chính',11,'introduce/introduce/',1,'banner',[now],1,1);
set @page_widgets16 = LAST_INSERT_ID();
INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Menu chính',3,'introduce/introduce/',1,'menu',[now],1,1);
set @page_widgets17 = LAST_INSERT_ID();
INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Sản phẩm',7,'economy/product/',1,'productall',[now],0,1);
set @page_widgets18 = LAST_INSERT_ID();
INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Tin tức',5,'news/news/',1,'newsall',[now],0,1);
set @page_widgets20 = LAST_INSERT_ID();
INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Social',5,'news/news/detail',1,'social',[now],0,1);
set @page_widgets24 = LAST_INSERT_ID();
INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Tin Tức Liên Quan',5,'news/news/detail',1,'newsrelation',[now],0,2);
set @page_widgets25 = LAST_INSERT_ID();
INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Form Liên hệ',5,'site/site/contact',1,'customform',[now],0,1);
set @page_widgets41 = LAST_INSERT_ID();
INSERT INTO page_widgets (page_widget_id, site_id,user_id, widget_title, position, page_key, widget_type, widget_id, created_time, showallpage, worder) VALUES (null,[site_id],[user_id],'Bản đồ',2,'site/site/contact',1,'map',[now],0,1);
set @page_widgets42 = LAST_INSERT_ID();

INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets16,[site_id],[user_id],CONCAT('{"banner_group_id":',@banner_groups3,',"showallpage":"1","widget_title":"Banner chính","show_wiget_title":"0"}'),[now],[now]);
INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets17,[site_id],[user_id],CONCAT('{"group_id":',@menu_groups3,',"directfrom":"left","showallpage":"1","widget_title":"Menu chính","show_wiget_title":"0"}'),[now],[now]);
INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets18,[site_id],[user_id],'{\"limit\":\"10\",\"showallpage\":\"0\",\"widget_title\":\"S\\u1ea3n ph\\u1ea9m\",\"show_wiget_title\":\"0\"}',[now],[now]);
INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets20,[site_id],[user_id],'{\"limit\":\"8\",\"showallpage\":\"0\",\"widget_title\":\"Tin t\\u1ee9c\",\"show_wiget_title\":\"0\"}',[now],[now]);
INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets24,[site_id],[user_id],'{\"showallpage\":\"0\",\"widget_title\":\"Social\",\"show_wiget_title\":\"0\"}',[now],[now]);
INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets25,[site_id],[user_id],'{\"limit\":\"4\",\"showallpage\":\"0\",\"widget_title\":\"Tin T\\u1ee9c Li\\u00ean Quan\",\"show_wiget_title\":\"1\"}',[now],[now]);
INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets41,[site_id],[user_id],CONCAT('{"form_id":',@forms2,',"labelClass":"4","showallpage":"0","widget_title":"Form Liên hệ","show_wiget_title":"0"}'),[now],[now]);
INSERT INTO page_widget_config (id, page_widget_id, site_id, user_id, config_data, created_time, modified_time) VALUES (null,@page_widgets42,[site_id],[user_id],'{\"limit\":\"3\",\"showallpage\":\"0\",\"widget_title\":\"B\\u1ea3n \\u0111\\u1ed3\",\"show_wiget_title\":\"0\"}',[now],[now]);

